# Generated by Django 3.0.5 on 2020-04-08 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='invited_user',
            new_name='invited',
        ),
    ]
