# Generated by Django 3.0.5 on 2020-04-08 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_room', '0002_auto_20200408_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='invited',
            field=models.ManyToManyField(related_name='invited_user', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
